GET http://localhost:3003/ping
###

GET http://localhost:3003/users
###

POST http://localhost:3003/users
Content-Type: application/json 

{
    "id": "u005",
    "name": "Euclana",
    "email": "clana@email.com",
    "password": "456654852"
}
###

GET http://localhost:3003/accounts
###